{
 "format": "cable-designer-project",
 "version": 1,
 "title_block": {
  "title": "CABLE ASSY, FCC TO PDU",
  "drawing_number": "W101-001",
  "revision": "A",
  "company": "ACME AEROSPACE (EXAMPLE)",
  "cage_code": "",
  "drawn_by": "K. KIPER",
  "date": "2026-10-08",
  "checked_by": "J. SMITH",
  "checked_date": "2026-10-08",
  "engineer": "",
  "engineer_date": "",
  "approved_by": "",
  "approved_date": "",
  "contract_number": "",
  "scale": "NONE",
  "weight": "",
  "next_assy": "A1000-001",
  "used_on": "FCC INSTALLATION",
  "statement": ""
 },
 "connectors": [
  {
   "ref": "P1",
   "connector_pn": "D38999/26WD18SN",
   "backshell_pn": "M85049/38S15W",
   "heatshrink_pn": "202K153-25/225-0",
   "label_pn": "TMS-SCE-1/2-2.0-9",
   "label_text": "W101-P1",
   "length": null,
   "description": "To flight computer J3",
   "contact_pn": ""
  },
  {
   "ref": "P2",
   "connector_pn": "D38999/26WD18PN",
   "backshell_pn": "M85049/38S15W",
   "heatshrink_pn": "202K153-25/225-0",
   "label_pn": "TMS-SCE-1/2-2.0-9",
   "label_text": "W101-P2",
   "length": null,
   "description": "To power distribution J7",
   "contact_pn": ""
  }
 ],
 "wires": [
  {
   "wire_id": "W1",
   "from_ref": "P1",
   "from_pin": "A",
   "to_ref": "P2",
   "to_pin": "A",
   "signal": "+28V PWR",
   "gauge": "20",
   "color": "RED",
   "wire_pn": "M22759/16-20-2",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": ""
  },
  {
   "wire_id": "W2",
   "from_ref": "P1",
   "from_pin": "B",
   "to_ref": "P2",
   "to_pin": "B",
   "signal": "28V RTN",
   "gauge": "20",
   "color": "BLK",
   "wire_pn": "M22759/16-20-0",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": ""
  },
  {
   "wire_id": "W3",
   "from_ref": "P1",
   "from_pin": "C",
   "to_ref": "P2",
   "to_pin": "C",
   "signal": "RS422 TX+",
   "gauge": "22",
   "color": "WHT",
   "wire_pn": "",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": "TSP1"
  },
  {
   "wire_id": "W4",
   "from_ref": "P1",
   "from_pin": "D",
   "to_ref": "P2",
   "to_pin": "D",
   "signal": "RS422 TX-",
   "gauge": "22",
   "color": "BLU",
   "wire_pn": "",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": "TSP1"
  },
  {
   "wire_id": "W5",
   "from_ref": "P1",
   "from_pin": "E",
   "to_ref": "P2",
   "to_pin": "E",
   "signal": "RS422 RX+",
   "gauge": "22",
   "color": "WHT",
   "wire_pn": "M22759/16-22-9",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": "TP2"
  },
  {
   "wire_id": "W6",
   "from_ref": "P1",
   "from_pin": "F",
   "to_ref": "P2",
   "to_pin": "F",
   "signal": "RS422 RX-",
   "gauge": "22",
   "color": "BLU",
   "wire_pn": "M22759/16-22-6",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": "TP2"
  },
  {
   "wire_id": "W7",
   "from_ref": "P1",
   "from_pin": "G",
   "to_ref": "P2",
   "to_pin": "H",
   "signal": "DISCRETE IN 1",
   "gauge": "22",
   "color": "WHT",
   "wire_pn": "M22759/16-22-9",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": ""
  },
  {
   "wire_id": "W8",
   "from_ref": "P1",
   "from_pin": "H",
   "to_ref": "P2",
   "to_pin": "G",
   "signal": "DISCRETE OUT 1",
   "gauge": "22",
   "color": "WHT",
   "wire_pn": "M22759/16-22-9",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": ""
  },
  {
   "wire_id": "W9",
   "from_ref": "P1",
   "from_pin": "J",
   "to_ref": "SP1",
   "to_pin": "",
   "signal": "SIG GND",
   "gauge": "22",
   "color": "BLK",
   "wire_pn": "M22759/16-22-0",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": ""
  },
  {
   "wire_id": "W10",
   "from_ref": "P1",
   "from_pin": "K",
   "to_ref": "P1",
   "to_pin": "L",
   "signal": "ADDR STRAP",
   "gauge": "22",
   "color": "WHT",
   "wire_pn": "M22759/16-22-9",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "JUMPER IN P1",
   "group": ""
  },
  {
   "wire_id": "W11",
   "from_ref": "P1",
   "from_pin": "M",
   "to_ref": "P2",
   "to_pin": "M",
   "signal": "CHASSIS GND",
   "gauge": "20",
   "color": "GRN",
   "wire_pn": "M22759/16-20-5",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": ""
  },
  {
   "wire_id": "W12",
   "from_ref": "SP1",
   "from_pin": "",
   "to_ref": "P2",
   "to_pin": "J",
   "signal": "SIG GND A",
   "gauge": "22",
   "color": "BLK",
   "wire_pn": "M22759/16-22-0",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": ""
  },
  {
   "wire_id": "W13",
   "from_ref": "SP1",
   "from_pin": "",
   "to_ref": "P2",
   "to_pin": "K",
   "signal": "SIG GND B",
   "gauge": "22",
   "color": "BLK",
   "wire_pn": "M22759/16-22-0",
   "length": null,
   "label_pn": "TMS-SCE-1/8-2.0-9",
   "heatshrink_pn": "",
   "notes": "",
   "group": ""
  }
 ],
 "groups": [
  {
   "group_id": "TSP1",
   "kind": "SHIELDED TWISTED PAIR",
   "cable_pn": "M27500-22TG2T14",
   "shield_pn": "",
   "shield_term_pn": "M83519/2-3",
   "term_from": "BACKSHELL",
   "term_to": "P2-L",
   "notes": "RS422 TX"
  },
  {
   "group_id": "TP2",
   "kind": "TWISTED PAIR",
   "cable_pn": "",
   "shield_pn": "",
   "shield_term_pn": "",
   "term_from": "",
   "term_to": "",
   "notes": "RS422 RX; 10 TWISTS PER FOOT MIN"
  }
 ],
 "splices": [
  {
   "ref": "SP1",
   "splice_pn": "M81824/1-1",
   "near": "P2",
   "distance": 6.0,
   "notes": "SIGNAL GROUND SPLICE"
  }
 ],
 "revisions": [
  {
   "rev": "A",
   "description": "INITIAL RELEASE",
   "date": "2026-10-08",
   "approved": "J. SMITH",
   "zone": ""
  }
 ],
 "notes": [
  "INTERPRET DRAWING PER ASME Y14.100.",
  "DIMENSIONS ARE IN {UNITS_NAME}. LENGTH TOLERANCE \u00b1{TOL} {UNITS}.",
  "WIRE PER WIRE LIST. TERMINATE CONTACTS PER CONNECTOR MANUFACTURER'S INSTRUCTIONS.",
  "100% CONTINUITY AND ISOLATION TEST PER WIRE LIST."
 ],
 "part_descriptions": {},
 "library": {
  "source": "parts_library.csv",
  "parts": [
   {
    "pn": "D38999/26WD18SN",
    "type": "connector",
    "description": "CONNECTOR, PLUG, 18 SKT",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "M39029/56-351",
    "contacts": 18.0,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "D38999/26WD18PN",
    "type": "connector",
    "description": "CONNECTOR, PLUG, 18 PIN",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "M39029/58-363",
    "contacts": 18.0,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M39029/56-351",
    "type": "contact",
    "description": "CONTACT, SOCKET, SIZE 20",
    "awg": null,
    "od": null,
    "awg_min": 20.0,
    "awg_max": 24.0,
    "dia_min": 0.04,
    "dia_max": 0.083,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M39029/58-363",
    "type": "contact",
    "description": "CONTACT, PIN, SIZE 20",
    "awg": null,
    "od": null,
    "awg_min": 20.0,
    "awg_max": 24.0,
    "dia_min": 0.04,
    "dia_max": 0.083,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M85049/38S15W",
    "type": "backshell",
    "description": "BACKSHELL, STRAIGHT, SHELL 15",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.14,
    "dia_max": 0.45,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "Dia = cable clamp range. EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "202K153-25/225-0",
    "type": "heatshrink",
    "description": "BOOT, HEATSHRINK, STRAIGHT",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.22,
    "dia_max": 0.6,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "Dia Min = recovered / Max = expanded (cable end). EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "TMS-SCE-1/2-2.0-9",
    "type": "label",
    "description": "SLEEVE, IDENTIFICATION, 1/2 IN",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.17,
    "dia_max": 0.47,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "TMS-SCE-1/8-2.0-9",
    "type": "marker",
    "description": "MARKER, WIRE, 1/8 IN",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.042,
    "dia_max": 0.125,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-20-0",
    "type": "wire",
    "description": "WIRE, 20 AWG, BLK",
    "awg": 20.0,
    "od": 0.062,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "BLK",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-20-2",
    "type": "wire",
    "description": "WIRE, 20 AWG, RED",
    "awg": 20.0,
    "od": 0.062,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "RED",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-20-5",
    "type": "wire",
    "description": "WIRE, 20 AWG, GRN",
    "awg": 20.0,
    "od": 0.062,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "GRN",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-22-0",
    "type": "wire",
    "description": "WIRE, 22 AWG, BLK",
    "awg": 22.0,
    "od": 0.052,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "BLK",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-22-2",
    "type": "wire",
    "description": "WIRE, 22 AWG, RED",
    "awg": 22.0,
    "od": 0.052,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "RED",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-22-6",
    "type": "wire",
    "description": "WIRE, 22 AWG, BLU",
    "awg": 22.0,
    "od": 0.052,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "BLU",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-22-9",
    "type": "wire",
    "description": "WIRE, 22 AWG, WHT",
    "awg": 22.0,
    "od": 0.052,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "WHT",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-24-5",
    "type": "wire",
    "description": "WIRE, 24 AWG, GRN",
    "awg": 24.0,
    "od": 0.046,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "GRN",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M22759/16-24-9",
    "type": "wire",
    "description": "WIRE, 24 AWG, WHT",
    "awg": 24.0,
    "od": 0.046,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "WHT",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M27500-22TG2T14",
    "type": "cable",
    "description": "CABLE, SHIELDED TWISTED PAIR, 22 AWG",
    "awg": 22.0,
    "od": 0.135,
    "awg_min": null,
    "awg_max": null,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": 2.0,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M81824/1-1",
    "type": "splice",
    "description": "SPLICE, CRIMP, ENVIRONMENT RESISTANT",
    "awg": null,
    "od": null,
    "awg_min": 20.0,
    "awg_max": 26.0,
    "dia_min": null,
    "dia_max": null,
    "cma_min": 300.0,
    "cma_max": 2100.0,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M83519/2-3",
    "type": "shield_term",
    "description": "SHIELD TERMINATION, SOLDER SLEEVE",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.09,
    "dia_max": 0.19,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "Dia = over shield. EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "MS3126F14-19S",
    "type": "connector",
    "description": "CONNECTOR, PLUG, 19 SKT",
    "awg": null,
    "od": null,
    "awg_min": 20.0,
    "awg_max": 24.0,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": 19.0,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "Contacts integral; AWG range on connector. EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "MS3126F10-6P",
    "type": "connector",
    "description": "CONNECTOR, PLUG, 6 PIN",
    "awg": null,
    "od": null,
    "awg_min": 20.0,
    "awg_max": 24.0,
    "dia_min": null,
    "dia_max": null,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": 6.0,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M85049/52-1-14W",
    "type": "backshell",
    "description": "BACKSHELL, SHELL 14",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.1,
    "dia_max": 0.39,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "M85049/52-1-10W",
    "type": "backshell",
    "description": "BACKSHELL, SHELL 10",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.07,
    "dia_max": 0.25,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "202K132-25/225-0",
    "type": "heatshrink",
    "description": "BOOT, HEATSHRINK, STRAIGHT",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.15,
    "dia_max": 0.55,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "202K121-25/225-0",
    "type": "heatshrink",
    "description": "BOOT, HEATSHRINK, STRAIGHT",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.1,
    "dia_max": 0.42,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   },
   {
    "pn": "TMS-SCE-3/8-2.0-9",
    "type": "label",
    "description": "SLEEVE, IDENTIFICATION, 3/8 IN",
    "awg": null,
    "od": null,
    "awg_min": null,
    "awg_max": null,
    "dia_min": 0.125,
    "dia_max": 0.375,
    "cma_min": null,
    "cma_max": null,
    "contact_pn": "",
    "contacts": null,
    "contacts_included": null,
    "conductors": null,
    "wall": null,
    "color": "",
    "cage": "",
    "notes": "EXAMPLE VALUES - VERIFY"
   }
  ]
 },
 "layout": {
  "P1": [
   0.0,
   0.0
  ],
  "P2": [
   640.0,
   0.0
  ],
  "SP1": [
   415.0,
   199.0
  ]
 },
 "sheet_size": "ANSI B (17 x 11 in)",
 "units": "IN",
 "tolerance": "0.5",
 "overall_length": 48.0
}